name: Commit

on: [push]

env:
  CI_NAME: Commit CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to SF
      run: |
        # sshpass -p '${{ secrets.SF_PASSWORD }}' scp -o StrictHostKeyChecking=no -r docs/* ${{ secrets.SF_USERNAME }}@web.sourceforge.net:/home/project-web/jianghuai/htdocs
        sshpass -p '${{ secrets.SF_PASSWORD }}' scp -o StrictHostKeyChecking=no docs/jianghuai/viewthread.html ${{ secrets.SF_USERNAME }}@web.sourceforge.net:/home/project-web/jianghuai/htdocs/jianghuai/